apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-tolerations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-tolerations
  template:
    metadata:
      labels:
        app: hello-world-tolerations
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "MyTaint"
        effect: "NoSchedule"